function q1 = integrate_ang_vel_measurement( ...
    q0, ...
    omega, ...
    delta_t ...
)
%INTEGRATE_ANG_VEL_MEASUREMENT
%Numerically integrate the quaternion using an angular velocity measurement
arguments
    q0 (4,1) double
    omega (3,1) double
    delta_t (1,1) double
end
options = odeset('RelTol', 1e-6, 'AbsTol', 1e-9);

[~,state] = ode113( ...
    @(t,y) quaternion_ang_vel_meas_state_derivative(t,y,omega),...
    [0 1e-9 delta_t], ...
    q0, ...
    options...
);
q1 = state(3,:)';
end

